<?php
return [
  "JWT_SECRET"=>env("JWT_SECRET"),
  "LOCALHOST"=>env("LOCALHOST"),
  "API.KAISERPAYMENT.COM"=>env("API.KAISERPAYMENT.COM"),
  "AGENT_TOOL.COM"=>env("AGENT_TOOL.COM"),
  "DASHBOARD.XEXON.IO"=>env("DASHBOARD.XEXON.IO"),
  "STG.XCREATOR.AI"=>env("STG.XCREATOR.AI"),  
];
